name: 'Setup Node.js and Install Dependencies'
description: 'Checkout code, setup Node.js 24, install npm 11.6.4, and install dependencies'

inputs:
  verify-lockfile:
    description: 'Verify lockfile integrity after installation'
    required: false
    default: 'true'
  install-command:
    description: 'npm command to install dependencies'
    required: false
    default: 'npm ci'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: '24'

    - name: Install npm 11.6.4
      shell: bash
      run: npm install -g npm@11.6.4

    - name: Install dependencies
      shell: bash
      run: ${{ inputs.install-command }}

    - name: Verify lockfile integrity
      if: inputs.verify-lockfile == 'true'
      shell: bash
      run: |
        if ! git diff --exit-code package-lock.json; then
          echo "❌ Error: package-lock.json was modified by npm ci"
          echo ""
          echo "This indicates a lockfile/package.json mismatch or npm version incompatibility."
          echo "Please regenerate package-lock.json with: npm install"
          echo ""
          echo "Changes detected:"
          git diff package-lock.json
          exit 1
        fi
        echo "✅ Lockfile integrity verified - no changes after npm ci"
